content/docs/admin/users/index.md, content/docs/user/about/index.md, content/docs/user/help/index.md, content/docs/user/overview/index.md, content/docs/user/profile/index.md, content/docs/user/reports/index.md
Modifications:
- Information doesn't take an s
- removed useless link to the pdf plugins guide
=> Fix typo with information and remove useless link to the plugins guide

content/tutorials/_includes/download_samples.md, content/tutorials/_includes/introduction.md, content/tutorials/bundle/index.md, content/tutorials/gradle/index.md, content/tutorials/maven/index.md, content/tutorials/sbt/index.md
Motivation:
* Users don't understand they have to download the artifact script file and that the artifact word is a link.
* Tutorials lack steps, it's one long block and it's easy to miss a step
* In maven, gradle and sbt tutorials, users are not made aware of the extra plugins they have to use with their existing projects.
Modifications:
* Use the `click here` words for calls to action
* Use the download word explicitly
* Split long blocks into sections
* Add a section for discovering the build plugins
Result:
Hopefully better UX
=> Improve tutorials, close MISC-72

layouts/partials/main/tutorials-meta.html, layouts/tutorials/single.html
**Motivation:**
Provide users a link pointing to the relevant section
**Modification:**
* Use partial headline-hash for content
* Add wrapping div with class `docs-content` for anchor css
---
=> Set anchors on tutorials titles and fix author `by` when there's none, closes MISC-74, closes MISC-75

assets/scss/common/_global.scss, content/tutorials/bundle/index.md, content/tutorials/gradle/index.md, content/tutorials/maven/index.md, content/tutorials/sbt/index.md, layouts/partials/sidebar/tutorials-menu.html, layouts/tutorials/single.html
=> Tutorials: center image, navigator and table of contents, closes MISC-77, closes MISC-78

content/tutorials/bundle/index.md, content/tutorials/gradle/index.md, content/tutorials/maven/index.md, content/tutorials/sbt/index.md, layouts/partials/sidebar/tutorials-menu.html
Motivation:
- Changing tutorials titles made it hard to figure out what tutorials are all about
Modification:
- Added a menutitle front matter parameter
- Used it in the left menu partial, with a fallback on real title if
undefined
=> Add a menutitle parameter for tutorials, close MISC-79

README.md, content/docs/admin/api-tokens/index.md, content/docs/admin/teams/index.md, content/docs/admin/users/index.md, content/docs/plugins/bamboo/index.md, content/docs/plugins/grafana/index.md, content/docs/plugins/jenkins/index.md, content/docs/plugins/script/index.md, content/docs/plugins/teamcity/index.md, content/docs/user/about/index.md, content/docs/user/api/index.md, content/docs/user/artifact_conf/index.md, content/docs/user/artifact_gen/index.md, content/docs/user/help/index.md, content/docs/user/login/index.md, content/docs/user/overview/index.md, content/docs/user/profile/index.md, content/docs/user/reports/index.md, content/docs/user/simulations/index.md, content/docs/user/trends/index.md
Motivation:
- previous and next buttons are not linking the correct pages
Modifications:
- Fixed the weight system: weight is compared globally, and not within a section
- added a part about the weight in the README
=> Fix next and previous button not linking the correct pages, closes MISC-88

content/docs/user/artifact_gen/index.md
- removes mention of SBT options which aren't needed when building an artifact manually
- also removes mention of `-J-Xss100M` because that's adressed a few lines below with `SBT_OPTS`
- plus a couple small tweaks while I was there
=> SBT artifact generation docs improvements, closes FL-559

content/tutorials/_includes/download_samples.md, content/tutorials/_includes/resources.md, content/tutorials/_includes/run.md, content/tutorials/_includes/simulation_1.md, content/tutorials/_includes/simulation_2.md, content/tutorials/_includes/upload.md, content/tutorials/bundle/index.md, content/tutorials/gradle/index.md, content/tutorials/maven/index.md, content/tutorials/sbt/index.md
Motivation:
- titles are missings because they are in included content
Modifications:
- there is no way for the toc to show titles in included content, so we need to put back the titles in the main page
=> Fix titles missing in the tutorials table of contents, closes MISC-81

content/reference/plugins/grafana/index.md
Motivation:
- recent versions of Grafana don't allow unisgned plugins
Modifications:
- added a link documenting how to allow unisnged plugin
=> Grafana plugin: mention how to load unsigned plugin

content/reference/_index.md, content/reference/plugins/bamboo/index.md, content/reference/plugins/grafana/index.md, content/reference/plugins/jenkins/index.md, content/reference/plugins/script/index.md, content/reference/plugins/teamcity/index.md
Motivation:
- ci plugins and grafana datasource were still linking an old version: 1.13.3
Modification:
- added a constant with the version of the plugins
- use the constant in jenkins, bamboo, teamcity, script and grafana doc
=> Update external plugins link to current version

README.md, go.mod
Motivation:
'hugo mod init' fails as-is and requires a workaround (removing the theme dependency).
Modifications:
Commit the go.mod file after successfully initializing the Hugo module. Also add the prerequisites to the readme file.
Result:
The commands mentioned in the readme should work as expected after checking out the repo.
=> Fix Hugo module init and readme

content/reference/plugins/grafana/index.md
Motivation:
- our samples uses the Gatling Enterprise datasource
- the plugin id is still frontline
=> Grafana datasource documentation: fix issues between FrontLine and Gatling Enterprise

content/tutorials/getting-started/index.md
Motivation:
- More user are using build tools than expected and gradle is more used than Maven
- Hence, we can't ignore them in the tutorial
Modification:
- Still mention the bundle is beginner friendly but explain how to
configure/download the samples
=> Mention build tools in the tutorial

content/reference/plugins/jenkins/index.md
Motivation:
Declarative syntax seems to be the way to go nowadays, even though Jenkins still also documents scripted syntax.
=> Provide Declarative Pipeline Syntax sample, close CLOUD-577

content/tutorials/getting-started/index.md
Modification:
- tutorial: regrouped package generation, upload an simulation creation in one step
- tutorial: use the new gatlingEnterpriseStart task for the build plugins
=> Update the tutorial with the new build plugin gatlingEnterpriseStart task

content/tutorials/getting-started/index.md
Motivation:
Documentation is outdated
Modifications:
Change the script's name to execute, and the name of the generated jar
Result:
The documentation is correlated with the bundle
=> chore: update shell script name in tutorial

content/reference/admin/private_locations/kubernetes_deployment/index.md
Motivation:
Controlplane are not able to delete jobs, we waiting for TTL
Modifications:
Add deletecollection verbs on resources jobs in control-plane-role
Result:
Better doc for better world.
=> doc: fix jobs deletion issue for private location on k8s

content/reference/admin/private_locations/configuration/kubernetes/index.md
Shortening the image name as it now contains both supported architectures.
Note that the name MUST be quoted as ':' is considered a key:value
separator in HOCON.
=> feat: introduce Docker images ARM support

content/reference/admin/private_locations/installation/ecs/index.md
Motivation:
- Required in order to be able to assign an instance profile to an EC2 instance
=> chore: Add iam:PassRole to the required policies on a control plane

content/reference/admin/private_locations/configuration/azure/index.md, content/reference/admin/private_locations/configuration/ec2/index.md, content/reference/admin/private_locations/configuration/kubernetes/index.md
[chore: document cloud-init reliance on Azure and AWS private locations](https://github.com/gatling/frontline-cloud-doc/commit/1f1ca874d6b4a3931df98351ceb2faf6e86f19b7)
[chore: document jvm-options and jvm-home private locations configurations](https://github.com/gatling/frontline-cloud-doc/commit/d10d5894d50d3b0e034bdd13b71690d3d62dd7fc) 
**Ref:** HYB-228
=> chore: document jvm-options and jvm-home private locations configurations

content/reference/admin/private_locations/configuration/ec2/index.md, content/reference/admin/private_locations/configuration/kubernetes/index.md
**Motivation:**
Document image requirements
**Modification:**
Document requirements:
- AWS: jq, curl, java and cloud init
- Kubernetes: jq, curl and java
- Azure: no custom images for now
=> chore: document image requirements, closes HYB-177

content/reference/admin/private_locations/configuration/ec2/index.md, content/reference/admin/private_locations/installation/ecs/index.md
[doc: add missing AWS EC2 permission to terminate instances](https://github.com/gatling/frontline-cloud-doc/commit/713dc8a85b36e01062e42a83905fbadd4873985a)
[doc: add AWS elastic ips configuration, closes HYB-325](https://github.com/gatling/frontline-cloud-doc/commit/071e6f401ea02d6cd7850223001f1b4f5eea69ae)
=> doc: add AWS elastic ips configuration, closes HYB-325

content/reference/admin/notifications/index.md
Adds an `info` alert that only users with the system admin role can enable Notifications
=> Add role level alert

content/reference/admin/private_locations/configuration/azure/index.md, content/reference/admin/private_locations/configuration/ec2/index.md, content/reference/admin/private_locations/configuration/kubernetes/index.md, content/reference/admin/private_locations/installation/kubernetes/index.md
Motivation:
- Some defaults are "wrong" and/or confusing
- Defaults should be commented
Modification:
- Add missing namespace in Deployment example
- Comment optional configuration
- Change defaults of optional configuration (Xmx8G -> Xmx4G, etc.)
=> chore: updates to the kubernetes part documentation of private locations

content/reference/admin/private_locations/configuration/gcp/index.md, content/reference/admin/private_locations/installation/gcp/index.md
[doc: troubleshooting on GCP installation](https://github.com/gatling/frontline-cloud-doc/commit/3e6baf3f83992e0aff08d708617220084ad14f35)
[doc: permissions base on specific configuration](https://github.com/gatling/frontline-cloud-doc/commit/3341f44399af21a0691e1af6aa71dc0fbb01ed41)
[doc: add instance template to GCP location configuration](https://github.com/gatling/frontline-cloud-doc/commit/98bf3dc12b536dd4deb4c0fef026cfb1d5398c9b)
=> doc: GCP location missing documentation

content/reference/admin/private_locations/configuration/ec2/index.md
[doc: references for Spot AWS private locations](https://github.com/gatling/frontline-cloud-doc/commit/cc67e9a3ccc62f5cefbd3074066f4124f08083a7)
[doc: remove VPC configuration from AWS private locations](https://github.com/gatling/frontline-cloud-doc/commit/32a7ab4e29be092290bcbccfe6bd58993f506dff)
=> doc: references for Spot AWS private locations

content/reference/admin/private_locations/installation/ecs/index.md
The IAM `Action`, `ec2:TerminateInstance`, is not a valid action.   `ec2:TerminateInstance` is the correct action.
=> Set the correct private_locations ECS installation IAM role action

content/reference/user/api/index.md, go.mod
Motivation:
Publish public API documentation on public documentation site
Modifications:
* Use the new swaggerui shortcode
Result:
OpenAPI documentation is publicly accessible and the user can try it
Wait for gatling/gatling.io-doc-theme#29
=> feat: add openapi

content/reference/admin/private_locations/private_packages/index.md
**Motivation:**
User need to configure outbound access to private repository sign URL when working with private packages.
=> doc: specify private package outbound connection URL for download

content/reference/admin/private_locations/aws/configuration/index.md, content/reference/admin/private_locations/azure/configuration/index.md, content/reference/admin/private_locations/dedicated/configuration/index.md, content/reference/admin/private_locations/gcp/configuration/index.md, content/reference/admin/private_locations/introduction/index.md, content/reference/admin/private_locations/kubernetes/configuration/index.md
Motivations:
* we don't recommend instance specs, resulting in customers running load generators on instances with not enough CPU.
* the instance types we highly in our configuration samples are either small cheap one or deprecated
Modification:
* Add specs for Private Locations type
* Update config sample with instance types that make sense
=> doc: add load generators specs

content/tutorials/gac-gradle/index.md
No hurry, but there it is so we don't forget it
=> doc: add private documentation for Gatling as Code (Gradle)

README.md, content/tutorials/gac-sbt/index.md, content/tutorials/gac/index.md, go.mod
Notes :
- Both documentation pages are private (one needs the direct link to access it)
- I didn't change Maven page path, since a client may be using it at this moment (`/cloud/tutorials/gac/`)
- Thus, I created the sbt page in `/cloud/tutorials/gac-sbt/`
We (@Isammoc and I) chose to create separate pages to suit our immediate needs, but duplicated content is never a good thing. May we think about a tab component as for code (Java / Scala), but generalized for other contexts ? Like Maven / sbt / Gradle ? cc @notdryft
=> doc: add documentation for Gatling as Code (sbt) and private locations
